# Generated by Django 3.1 on 2020-09-03 20:06

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followauthor',
            name='author',
        ),
        migrations.AddField(
            model_name='followauthor',
            name='authors',
            field=models.ManyToManyField(related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Избранный автор'),
        ),
    ]
