# Generated by Django 3.1 on 2020-09-05 21:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0003_auto_20200906_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followauthor',
            name='authors',
            field=models.ManyToManyField(blank=True, related_name='following', to=settings.AUTH_USER_MODEL, verbose_name='Избранный автор'),
        ),
    ]
