# Generated by Django 3.1 on 2020-09-06 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200906_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followauthor',
            options={'ordering': ['-authors__recipes'], 'verbose_name': 'Подписка на автора', 'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
