# Generated by Django 3.1 on 2020-09-06 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200907_0007'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='followauthor',
            options={'verbose_name': 'Подписка на автора', 'verbose_name_plural': 'Подписки на авторов'},
        ),
    ]
