# Generated by Django 3.1 on 2020-09-02 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='coock_time',
            new_name='cook_time',
        ),
    ]
