# Generated by Django 3.1 on 2020-09-03 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='color',
            field=models.CharField(default='orange', max_length=255, verbose_name='Цвет'),
            preserve_default=False,
        ),
    ]
