# Generated by Django 3.1 on 2020-09-04 14:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_favoriterecipes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='favoriterecipes',
            options={'verbose_name': 'Избранный рецепт', 'verbose_name_plural': 'Избранные рецепты'},
        ),
    ]
