# Generated by Django 3.1 on 2020-09-07 19:10
import json
from django.db import migrations, transaction


def add_ingredients(apps, schema_editor):
    Ingredient = apps.get_model('recipes', 'Ingredient')
    Ingredient.objects.all().delete()
    with open('ingredients.json', encoding='utf-8') as file:
        ingredients = json.load(file)
        for ingredient in ingredients:
            with transaction.atomic():
                Ingredient.objects.create(
                    title=ingredient['title'],
                    dimension=ingredient['dimension'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('recipes', '0013_auto_20200907_0039'),
    ]

    operations = [
        migrations.RunPython(add_ingredients),
    ]
