# Generated by Django 3.1 on 2020-09-08 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0014_auto_20200907_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'ordering': ['id'], 'verbose_name': 'Тег', 'verbose_name_plural': 'Теги'},
        ),
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='breakfast', verbose_name='Уникальный адрес'),
            preserve_default=False,
        ),
    ]
