# Generated by Django 3.1 on 2020-09-11 16:47

import json

from django.db import migrations, transaction


def add_tags(apps, schema_editor):
    Tag = apps.get_model('recipes', 'Tag')
    Tag.objects.all().delete()
    with open('tags.json', encoding='utf-8') as file:
        tags = json.load(file)
        for tag in tags:
            with transaction.atomic():
                Tag.objects.create(
                    name=tag['fields']['title'], style=tag['fields']['color'],
                    slug=tag['fields']['slug'])


class Migration(migrations.Migration):
    atomic = False

    dependencies = [
        ('recipes', '0017_auto_20200910_1929'),
    ]

    operations = [
        migrations.RunPython(add_tags),
    ]
